name: PR build

on:
  push:
    branches: [develop]
  pull_request:
    branches:
      - develop
      - main

jobs:
  server:
    name: Build Server
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: Run tests
        run: |
          yarn install --frozen-lockfile
          yarn build
